#!/bin/bash

if [ x"$@" = x">> documentation" ];
then
killall rofi
sleep 0.25
rofi-sensible-terminal -e "mxfb-help"
kill rofi-sensible-terminal
fi

if [ x"$@" = x">> theme selector" ];
then
killall rofi
sleep 0.25
rofi-sensible-terminal -e "rofi-theme-selector"
kill rofi-sensible-terminal
fi

if [ x"$@" = x">> general help" ];
then
killall rofi
sleep 0.25
mx-viewer https://mxlinux.org/wiki/help-files/help-rofi/
kill mx-viewer
fi

if [ x"$@" = x">> scripts" ];
then
killall rofi
sleep 0.25
rofi-sensible-terminal -e "man rofi-script"
kill rofi-sensible-terminal
fi

if [ x"$@" = x">> recolor" ];
then
killall rofi
sleep 0.25
rofi-sensible-terminal -e "mxrr"
kill rofi-sensible-terminal
fi

if [ x"$@" = x">> theme format" ];
then
killall rofi
sleep 0.25
rofi-sensible-terminal -e "man rofi-theme"
kill rofi-sensible-terminal
fi

if [ x"$@" = x">> detailed help" ];
then
killall rofi
sleep 0.25
rofi-sensible-terminal -e "man rofi"
kill rofi-sensible-terminal
fi

if [ x"$@" = x">> hints" ];
then
killall rofi
sleep 0.25
featherpad ~/.config/rofi/hints
kill featherpad
fi

echo "ROFI"
echo ">> hints"
echo ">> general help"
echo ">> detailed help"
echo ">> theme selector"
echo ">> theme format"
echo ">> recolor"
echo ">> scripts"

echo "MX-FLUXBOX"
echo ">> documentation"
